name: Continuous integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout 
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: prepare dependencies
      run: sudo apt-get -y --no-install-recommends install build-essential git cmake ninja-build qt6-base-dev libqscintilla2-qt6-dev
    - name: cmake
      run: cmake -GNinja .
    - name: cmake build
      run: cmake --build . -j $(nproc)
